/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSendingPanelRouteImport } from './routes/_authenticated/sending-panel'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns.$campaignId'
import { Route as ApiPublicWebhooksZiontalkRouteImport } from './routes/api/public/webhooks/ziontalk'
import { Route as ApiPublicHooksProcessQueueRouteImport } from './routes/api/public/hooks/process-queue'
import { Route as AuthenticatedCampaignsCampaignIdSettingsRouteImport } from './routes/_authenticated/campaigns.$campaignId.settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSendingPanelRoute =
  AuthenticatedSendingPanelRouteImport.update({
    id: '/sending-panel',
    path: '/sending-panel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebhooksZiontalkRoute =
  ApiPublicWebhooksZiontalkRouteImport.update({
    id: '/api/public/webhooks/ziontalk',
    path: '/api/public/webhooks/ziontalk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessQueueRoute =
  ApiPublicHooksProcessQueueRouteImport.update({
    id: '/api/public/hooks/process-queue',
    path: '/api/public/hooks/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCampaignsCampaignIdSettingsRoute =
  AuthenticatedCampaignsCampaignIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sending-panel': typeof AuthenticatedSendingPanelRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/campaigns/$campaignId/settings': typeof AuthenticatedCampaignsCampaignIdSettingsRoute
  '/api/public/hooks/process-queue': typeof ApiPublicHooksProcessQueueRoute
  '/api/public/webhooks/ziontalk': typeof ApiPublicWebhooksZiontalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sending-panel': typeof AuthenticatedSendingPanelRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/campaigns/$campaignId/settings': typeof AuthenticatedCampaignsCampaignIdSettingsRoute
  '/api/public/hooks/process-queue': typeof ApiPublicHooksProcessQueueRoute
  '/api/public/webhooks/ziontalk': typeof ApiPublicWebhooksZiontalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sending-panel': typeof AuthenticatedSendingPanelRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/campaigns/$campaignId/settings': typeof AuthenticatedCampaignsCampaignIdSettingsRoute
  '/api/public/hooks/process-queue': typeof ApiPublicHooksProcessQueueRoute
  '/api/public/webhooks/ziontalk': typeof ApiPublicWebhooksZiontalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/channels'
    | '/contacts'
    | '/dashboard'
    | '/inbox'
    | '/reports'
    | '/sending-panel'
    | '/settings'
    | '/campaigns/$campaignId'
    | '/campaigns/'
    | '/campaigns/$campaignId/settings'
    | '/api/public/hooks/process-queue'
    | '/api/public/webhooks/ziontalk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/channels'
    | '/contacts'
    | '/dashboard'
    | '/inbox'
    | '/reports'
    | '/sending-panel'
    | '/settings'
    | '/campaigns/$campaignId'
    | '/campaigns'
    | '/campaigns/$campaignId/settings'
    | '/api/public/hooks/process-queue'
    | '/api/public/webhooks/ziontalk'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/channels'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/reports'
    | '/_authenticated/sending-panel'
    | '/_authenticated/settings'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/campaigns/'
    | '/_authenticated/campaigns/$campaignId/settings'
    | '/api/public/hooks/process-queue'
    | '/api/public/webhooks/ziontalk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksProcessQueueRoute: typeof ApiPublicHooksProcessQueueRoute
  ApiPublicWebhooksZiontalkRoute: typeof ApiPublicWebhooksZiontalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sending-panel': {
      id: '/_authenticated/sending-panel'
      path: '/sending-panel'
      fullPath: '/sending-panel'
      preLoaderRoute: typeof AuthenticatedSendingPanelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/ziontalk': {
      id: '/api/public/webhooks/ziontalk'
      path: '/api/public/webhooks/ziontalk'
      fullPath: '/api/public/webhooks/ziontalk'
      preLoaderRoute: typeof ApiPublicWebhooksZiontalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-queue': {
      id: '/api/public/hooks/process-queue'
      path: '/api/public/hooks/process-queue'
      fullPath: '/api/public/hooks/process-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns/$campaignId/settings': {
      id: '/_authenticated/campaigns/$campaignId/settings'
      path: '/settings'
      fullPath: '/campaigns/$campaignId/settings'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
  }
}

interface AuthenticatedCampaignsCampaignIdRouteChildren {
  AuthenticatedCampaignsCampaignIdSettingsRoute: typeof AuthenticatedCampaignsCampaignIdSettingsRoute
}

const AuthenticatedCampaignsCampaignIdRouteChildren: AuthenticatedCampaignsCampaignIdRouteChildren =
  {
    AuthenticatedCampaignsCampaignIdSettingsRoute:
      AuthenticatedCampaignsCampaignIdSettingsRoute,
  }

const AuthenticatedCampaignsCampaignIdRouteWithChildren =
  AuthenticatedCampaignsCampaignIdRoute._addFileChildren(
    AuthenticatedCampaignsCampaignIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSendingPanelRoute: typeof AuthenticatedSendingPanelRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSendingPanelRoute: AuthenticatedSendingPanelRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCampaignsCampaignIdRoute:
    AuthenticatedCampaignsCampaignIdRouteWithChildren,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksProcessQueueRoute: ApiPublicHooksProcessQueueRoute,
  ApiPublicWebhooksZiontalkRoute: ApiPublicWebhooksZiontalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
